// export const CU_THICK = 5.123 // [um]
export const AL_DENSITY = 2.7 // [g * cm^-3]
export const CU_DENSITY = 8.96 // [g * cm^-3]
export const ELECTROLITE_DENSITY = 1.5 // [g * cm^-3]
export const SEPARATOR_DENSITY = 0.97 // [g * cm^-3]
export const CATHODE_POROSITY = 0.3 // []
export const ANODE_POROSITY = 0.3 // []
export const SEPARATOR_POROSITY = 0.55 // []
export const COAT_THICKNESS = 50 // [um]

//provisorias hasta api
export const PR_s_rate_anode_capacity = 145 // [mA*h*g^-1]
export const PR_s_rate_cathode_capacity = 175 // [mA*h*g^-1]
export const PR_s_rate_charge_voltage = 2.35 // [V]
export const PR_s_rate_discharge_voltage = 2.3 // [V]
export const PR_current_min = 0.014 // [A]
export const PR_current_max = 0.7 // [A]
export const PR_f_rate_cathode_capacity = 130 // [mA*h*g^-1]
export const PR_f_rate_charge_voltage = 4 // [V]
export const PR_f_rate_discharge_voltage = 2.2 // [V]
